# -*- coding: UTF-8 -*-
# generated by lino.sphinxcontrib.help_text_builder
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

help_texts = {
    'lino_mercato.lib.mercato.Plugin' : _("""See lino.core.plugin.Plugin."""),
    'lino_mercato.lib.contacts.Worker' : _("""The Django model which represents a worker."""),
}
